### ISSUE TITLE
PHP-FPM Plugin

### ISSUE THREAD

**Issue by caleuanhopkins** [mackerelio/docker-mackerel-agent#2]
PHP-FPM plugin (https://github.com/mackerelio/mackerel-agent-plugins/tree/master/mackerel-plugin-php-fpm) appears to be missing in the docker image:

<img width="1137" alt="screen shot 2017-02-18 at 10 22 52" src="https://cloud.githubusercontent.com/assets/1164525/23092494/3abd502e-f5c4-11e6-8ebe-7e49385a8d49.png">

**Comment by astj** [comment]
@caleuanhopkins 
Thank you for reporting.

At first, I'd like to clear which Docker image are you using.
In fact [`docker pull mackerel/mackerel-agent`](https://hub.docker.com/r/mackerel/mackerel-agent/~/dockerfile/) doesn't use this repository, but [stanaka/docker-mackerel-agent](https://github.com/stanaka/docker-mackerel-agent).
Are you using stanaka/docker-mackerel-agent, or exact this repository?

And second, if you're using stanaka/docker-mackerel-agent, which tag(version) of the Docker image are you using?
mackerel-plugin-php-fpm is added on mackerel-agent-plugin 0.21.0 ([ref](https://github.com/mackerelio/mackerel-agent-plugins/releases/tag/v0.21.0)).
Due to our release cycle, Docker Image `mackerel/mackerel-agnet` with tag >= 0.33.0 and latest should include mackerel-agent-plugin >= 0.21.0.

Here is my result with the latest image. It looks there's `mackerel-plugin-php-fpm` available.
```
$ docker run -it mackerel/mackerel-agent bash
[root@0414a6cf5155 /]# mackerel-
mackerel-agent                     mackerel-plugin-graphite           mackerel-plugin-php-opcache
mackerel-plugin-apache2            mackerel-plugin-haproxy            mackerel-plugin-plack
mackerel-plugin-aws-cloudfront     mackerel-plugin-inode              mackerel-plugin-postgres
mackerel-plugin-aws-ec2-cpucredit  mackerel-plugin-jmx-jolokia        mackerel-plugin-proc-fd
mackerel-plugin-aws-ec2-ebs        mackerel-plugin-jvm                mackerel-plugin-rabbitmq
mackerel-plugin-aws-elasticache    mackerel-plugin-linux              mackerel-plugin-redis
mackerel-plugin-aws-elasticsearch  mackerel-plugin-mailq              mackerel-plugin-snmp
mackerel-plugin-aws-elb            mackerel-plugin-memcached          mackerel-plugin-squid
mackerel-plugin-aws-rds            mackerel-plugin-mongodb            mackerel-plugin-td-table-count
mackerel-plugin-aws-ses            mackerel-plugin-multicore          mackerel-plugin-trafficserver
mackerel-plugin-conntrack          mackerel-plugin-munin              mackerel-plugin-twemproxy
mackerel-plugin-docker             mackerel-plugin-mysql              mackerel-plugin-unicorn
mackerel-plugin-elasticsearch      mackerel-plugin-nginx              mackerel-plugin-uptime
mackerel-plugin-fluentd            mackerel-plugin-php-apc            mackerel-plugin-varnish
mackerel-plugin-gostats            mackerel-plugin-php-fpm            mackerel-plugin-xentop
```

**Comment by caleuanhopkins** [comment]
hey, thanks for getting back. I'm using the `mackerel/mackerel-agent` image. Do you suggest that I use the `stanaka/docker-mackerel-agent` instead?

**Comment by astj** [comment]
Oh, sorry for confusing.
- `docker pull mackerel/mackerel-agent` = https://github.com/stanaka/docker-mackerel-agent
  - There's a historical reason...
- Docker images by this repository is not registered on Docker Hub
- We suggest using `docker pull mackerel/mackerel-agent`, which is actually github.com/stanaka/docker-mackerel-agent

So, if you're using `mackerel/mackerel-agent` Docker image, it's the right one.
